Make sure _MSC_VER is defined before checking
Avoids the following:

error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]
   59 | #if _MSC_VER <= 1900
      |     ^~~~~~~~